// Copyright 2026 The Inkwall Authors
// SPDX-License-Identifier: Apache-2.0

// The engine's own check API (0006 §5). A proxy without a native protocol
// describes one client request in a CheckRequest and acts on the verdict in
// the CheckResponse. Served as POST /v1/check with a protobuf or JSON body.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: engine/v1/engine.proto

package enginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action tells the proxy what to do with the request.
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	// Forward the request.
	Action_ACTION_ALLOW Action = 1
	// Reject the request with CheckResponse.status.
	Action_ACTION_DENY Action = 2
	// Forward the request; it would have been blocked in block mode.
	Action_ACTION_LOG Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ALLOW",
		2: "ACTION_DENY",
		3: "ACTION_LOG",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ALLOW":       1,
		"ACTION_DENY":        2,
		"ACTION_LOG":         3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_v1_engine_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_engine_v1_engine_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{0}
}

// Reason explains a verdict.
type Reason int32

const (
	Reason_REASON_UNSPECIFIED Reason = 0
	// No rule interrupted the request.
	Reason_REASON_NONE Reason = 1
	// A rule interrupted the request.
	Reason_REASON_RULE Reason = 2
	// Inspection exceeded the deadline.
	Reason_REASON_TIMEOUT Reason = 3
	// The evaluator failed.
	Reason_REASON_ERROR Reason = 4
	// The caller canceled the check.
	Reason_REASON_CANCELED Reason = 5
	// All evaluation slots were busy; the request was not inspected.
	Reason_REASON_OVERLOAD Reason = 6
	// The body was longer than the inspection limit.
	Reason_REASON_OVERSIZE Reason = 7
	// The route is configured to skip inspection.
	Reason_REASON_SKIPPED Reason = 8
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_NONE",
		2: "REASON_RULE",
		3: "REASON_TIMEOUT",
		4: "REASON_ERROR",
		5: "REASON_CANCELED",
		6: "REASON_OVERLOAD",
		7: "REASON_OVERSIZE",
		8: "REASON_SKIPPED",
	}
	Reason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"REASON_NONE":        1,
		"REASON_RULE":        2,
		"REASON_TIMEOUT":     3,
		"REASON_ERROR":       4,
		"REASON_CANCELED":    5,
		"REASON_OVERLOAD":    6,
		"REASON_OVERSIZE":    7,
		"REASON_SKIPPED":     8,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_v1_engine_proto_enumTypes[1].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_engine_v1_engine_proto_enumTypes[1]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{1}
}

// CheckRequest describes one client request as the proxy received it.
type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates the request across proxy, engine and events. Empty or unsafe
	// values (anything but 1-128 of [A-Za-z0-9._:-]) are replaced by a
	// generated ID, returned in CheckResponse.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// HTTP method, e.g. "GET".
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// "http" or "https" as seen by the proxy. Empty means "http".
	Scheme string `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// Request authority (Host header or :authority).
	Authority string `protobuf:"bytes,4,opt,name=authority,proto3" json:"authority,omitempty"`
	// Path and query exactly as received, before any normalization. Must be in
	// origin form ("/path?query") and must not contain a fragment.
	RawUri string `protobuf:"bytes,5,opt,name=raw_uri,json=rawUri,proto3" json:"raw_uri,omitempty"`
	// Request headers in received order. A Host header is ignored in favour of
	// authority. Send Content-Length and Transfer-Encoding as received: rules
	// check for their presence.
	Headers []*Header `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	// End client address after the proxy's own trusted-proxy resolution, e.g.
	// "203.0.113.7" or "2001:db8::1". Empty means peer_ip.
	ClientIp string `protobuf:"bytes,7,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// Address of the proxy's direct TCP peer.
	PeerIp string `protobuf:"bytes,8,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`
	// Body prefix. Bytes beyond the engine's --max-body-bytes are dropped and
	// the body is treated as truncated.
	Body []byte `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	// The real body was longer than body.
	BodyTruncated bool `protobuf:"varint,10,opt,name=body_truncated,json=bodyTruncated,proto3" json:"body_truncated,omitempty"`
	// Reserved for selecting a policy by route once bundles exist; ignored.
	RouteHint string `protobuf:"bytes,11,opt,name=route_hint,json=routeHint,proto3" json:"route_hint,omitempty"`
	// Protocol version, e.g. "HTTP/1.1" or "HTTP/2.0". Empty means "HTTP/1.1".
	Protocol      string `protobuf:"bytes,12,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_engine_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CheckRequest) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *CheckRequest) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *CheckRequest) GetRawUri() string {
	if x != nil {
		return x.RawUri
	}
	return ""
}

func (x *CheckRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CheckRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *CheckRequest) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *CheckRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CheckRequest) GetBodyTruncated() bool {
	if x != nil {
		return x.BodyTruncated
	}
	return false
}

func (x *CheckRequest) GetRouteHint() string {
	if x != nil {
		return x.RouteHint
	}
	return ""
}

func (x *CheckRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// Header is one request or response header field.
type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Value, when it is valid UTF-8.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Value as raw bytes, for values that are not valid UTF-8 (obs-text).
	// Takes precedence over value when set.
	RawValue      []byte `protobuf:"bytes,3,opt,name=raw_value,json=rawValue,proto3" json:"raw_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_engine_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Header) GetRawValue() []byte {
	if x != nil {
		return x.RawValue
	}
	return nil
}

// CheckResponse is the verdict for one CheckRequest.
type CheckResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=inkwall.engine.v1.Action" json:"action,omitempty"`
	// HTTP status to return to the client when action is ACTION_DENY.
	Status uint32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// Headers to add to the forwarded request (allow, log) or to the denial.
	ResponseHeaders []*Header `protobuf:"bytes,3,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty"`
	// Every rule that matched, including rules that only added to an anomaly
	// score.
	RuleIds []uint32 `protobuf:"varint,4,rep,packed,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
	Reason  Reason   `protobuf:"varint,5,opt,name=reason,proto3,enum=inkwall.engine.v1.Reason" json:"reason,omitempty"`
	// Rule that interrupted the request, or 0.
	InterruptingRuleId uint32 `protobuf:"varint,6,opt,name=interrupting_rule_id,json=interruptingRuleId,proto3" json:"interrupting_rule_id,omitempty"`
	// The request ID used in the engine's events.
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Time spent inspecting.
	InspectionTime *durationpb.Duration `protobuf:"bytes,8,opt,name=inspection_time,json=inspectionTime,proto3" json:"inspection_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_engine_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_engine_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResponse) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *CheckResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CheckResponse) GetResponseHeaders() []*Header {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *CheckResponse) GetRuleIds() []uint32 {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

func (x *CheckResponse) GetReason() Reason {
	if x != nil {
		return x.Reason
	}
	return Reason_REASON_UNSPECIFIED
}

func (x *CheckResponse) GetInterruptingRuleId() uint32 {
	if x != nil {
		return x.InterruptingRuleId
	}
	return 0
}

func (x *CheckResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CheckResponse) GetInspectionTime() *durationpb.Duration {
	if x != nil {
		return x.InspectionTime
	}
	return nil
}

var File_engine_v1_engine_proto protoreflect.FileDescriptor

const file_engine_v1_engine_proto_rawDesc = "" +
	"\n" +
	"\x16engine/v1/engine.proto\x12\x11inkwall.engine.v1\x1a\x1egoogle/protobuf/duration.proto\"\xf5\x02\n" +
	"\fCheckRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12\x1c\n" +
	"\tauthority\x18\x04 \x01(\tR\tauthority\x12\x17\n" +
	"\araw_uri\x18\x05 \x01(\tR\x06rawUri\x123\n" +
	"\aheaders\x18\x06 \x03(\v2\x19.inkwall.engine.v1.HeaderR\aheaders\x12\x1b\n" +
	"\tclient_ip\x18\a \x01(\tR\bclientIp\x12\x17\n" +
	"\apeer_ip\x18\b \x01(\tR\x06peerIp\x12\x12\n" +
	"\x04body\x18\t \x01(\fR\x04body\x12%\n" +
	"\x0ebody_truncated\x18\n" +
	" \x01(\bR\rbodyTruncated\x12\x1d\n" +
	"\n" +
	"route_hint\x18\v \x01(\tR\trouteHint\x12\x1a\n" +
	"\bprotocol\x18\f \x01(\tR\bprotocol\"O\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\traw_value\x18\x03 \x01(\fR\brawValue\"\x83\x03\n" +
	"\rCheckResponse\x121\n" +
	"\x06action\x18\x01 \x01(\x0e2\x19.inkwall.engine.v1.ActionR\x06action\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12D\n" +
	"\x10response_headers\x18\x03 \x03(\v2\x19.inkwall.engine.v1.HeaderR\x0fresponseHeaders\x12\x19\n" +
	"\brule_ids\x18\x04 \x03(\rR\aruleIds\x121\n" +
	"\x06reason\x18\x05 \x01(\x0e2\x19.inkwall.engine.v1.ReasonR\x06reason\x120\n" +
	"\x14interrupting_rule_id\x18\x06 \x01(\rR\x12interruptingRuleId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12B\n" +
	"\x0finspection_time\x18\b \x01(\v2\x19.google.protobuf.DurationR\x0einspectionTime*S\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_ALLOW\x10\x01\x12\x0f\n" +
	"\vACTION_DENY\x10\x02\x12\x0e\n" +
	"\n" +
	"ACTION_LOG\x10\x03*\xbb\x01\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vREASON_NONE\x10\x01\x12\x0f\n" +
	"\vREASON_RULE\x10\x02\x12\x12\n" +
	"\x0eREASON_TIMEOUT\x10\x03\x12\x10\n" +
	"\fREASON_ERROR\x10\x04\x12\x13\n" +
	"\x0fREASON_CANCELED\x10\x05\x12\x13\n" +
	"\x0fREASON_OVERLOAD\x10\x06\x12\x13\n" +
	"\x0fREASON_OVERSIZE\x10\a\x12\x12\n" +
	"\x0eREASON_SKIPPED\x10\b2Z\n" +
	"\fCheckService\x12J\n" +
	"\x05Check\x12\x1f.inkwall.engine.v1.CheckRequest\x1a .inkwall.engine.v1.CheckResponseB7Z5github.com/inkwall-dev/inkwall/api/engine/v1;enginev1b\x06proto3"

var (
	file_engine_v1_engine_proto_rawDescOnce sync.Once
	file_engine_v1_engine_proto_rawDescData []byte
)

func file_engine_v1_engine_proto_rawDescGZIP() []byte {
	file_engine_v1_engine_proto_rawDescOnce.Do(func() {
		file_engine_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_v1_engine_proto_rawDesc), len(file_engine_v1_engine_proto_rawDesc)))
	})
	return file_engine_v1_engine_proto_rawDescData
}

var file_engine_v1_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_engine_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_engine_v1_engine_proto_goTypes = []any{
	(Action)(0),                 // 0: inkwall.engine.v1.Action
	(Reason)(0),                 // 1: inkwall.engine.v1.Reason
	(*CheckRequest)(nil),        // 2: inkwall.engine.v1.CheckRequest
	(*Header)(nil),              // 3: inkwall.engine.v1.Header
	(*CheckResponse)(nil),       // 4: inkwall.engine.v1.CheckResponse
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_engine_v1_engine_proto_depIdxs = []int32{
	3, // 0: inkwall.engine.v1.CheckRequest.headers:type_name -> inkwall.engine.v1.Header
	0, // 1: inkwall.engine.v1.CheckResponse.action:type_name -> inkwall.engine.v1.Action
	3, // 2: inkwall.engine.v1.CheckResponse.response_headers:type_name -> inkwall.engine.v1.Header
	1, // 3: inkwall.engine.v1.CheckResponse.reason:type_name -> inkwall.engine.v1.Reason
	5, // 4: inkwall.engine.v1.CheckResponse.inspection_time:type_name -> google.protobuf.Duration
	2, // 5: inkwall.engine.v1.CheckService.Check:input_type -> inkwall.engine.v1.CheckRequest
	4, // 6: inkwall.engine.v1.CheckService.Check:output_type -> inkwall.engine.v1.CheckResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_engine_v1_engine_proto_init() }
func file_engine_v1_engine_proto_init() {
	if File_engine_v1_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_v1_engine_proto_rawDesc), len(file_engine_v1_engine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_v1_engine_proto_goTypes,
		DependencyIndexes: file_engine_v1_engine_proto_depIdxs,
		EnumInfos:         file_engine_v1_engine_proto_enumTypes,
		MessageInfos:      file_engine_v1_engine_proto_msgTypes,
	}.Build()
	File_engine_v1_engine_proto = out.File
	file_engine_v1_engine_proto_goTypes = nil
	file_engine_v1_engine_proto_depIdxs = nil
}
